language: en

pipeline:
  - name: HFTransformersNLP
    model_name: "distilbert"
    model_weights: "distilbert-base-uncased"
  - name: "LanguageModelTokenizer"
  - name: "LanguageModelFeaturizer"
  - name: "DIETClassifier"
    "epochs": 200
  - name: "ResponseSelector"


policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy 
